language: java
sudo: required
script: ant main
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: chiranjeevi.v.desaraju@verizon.com
  password: gundu1526
  organization: titus_hackathon_legends
  space: development
  file: build/jar/HelloHackathon.jar
  on:
    repo: KrishnaHarishK/LegendsHackathon